version: '2.1'

services:
  db:
    image: mysql:5.7
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    healthcheck: 
        test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-ppassword"]
        timeout: 20s
        retries: 10 
    
  gallery: 
    build: .
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
